version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: relay-postgres

    environment:
      POSTGRES_USER: relay
      POSTGRES_PASSWORD: relay123
      POSTGRES_DB: relay

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: